{% set name = "striprtf" %}
{% set version = "0.0.27" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/striprtf-{{ version }}.tar.gz
  sha256: cb7653dda023fd3e2c6455d2bac2580fb1c624774a78b249e815890c9dc37669

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - striprtf
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/joshy/striprtf
  summary: A simple library to convert rtf to text
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
